### ISSUE TITLE
Request for Remmina (protocol icons)

### ISSUE THREAD

**Issue by Issam2204** [franksouza183/EvolvereSuit#114] opened 2015-04-17 19:33 UTC
Hello! I must say I've never seen a more beautiful and complete set of icons! You redesigned my complete desktop! Thank you so much!

The request is for Remote Desktop Client (precisely when I open the program and create a new connection, under "Protocol" I see the old ugly icons).

This is not essential, but it's a minor issue from making this icons set truly PERFECT for my usage :-)

Thank you again for your hard work!

**Comment by franksouza183** [comment] 2015-04-17 21:26
duplicate of #53 #52 #56 #39 

Please, open a new issue for Orca and Remmina protocols icons (you can keep this issue for it, just edit the description)

Thank you for the feedback!! ;)

**Comment by Issam2204** [comment] 2015-04-17 21:30
Done as requested :)

Thank you very much!

**Comment by franksouza183** [comment] 2015-04-17 21:32
Thanks, but I guess I did not explain well. Please, create a new isse for Orca, and keep this for reminna

Sorry XD

**Comment by franksouza183** [comment] 2015-04-17 21:33
just remember, one issue for each icon (or app specific) request

**Comment by Issam2204** [comment] 2015-04-17 21:33
Oh, sorry :)

I'll do it right away. Sorry again :)

**Comment by franksouza183** [comment] 2015-04-17 21:34
Absolutely no problem ;)

**Comment by franksouza183** [comment] 2018-02-15 06:43
on new repo

**Closed as completed by franksouza183** 2018-02-15 06:43 UTC
Labels: Icon request
